# This is a basic workflow to help you get started with Actions

name: Build with slack notification setup

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # build job
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: '14.15'
      # Install the dependencies need to build the app
      - name: Install Dependencies
        run: npm install
      # Runs a set of commands to build
      - name: Build
        run: npm run build --prod --localize
      # sotre the artifact
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: public
          path: ./public
      # We have to do it like that... https://github.com/rtCamp/action-slack-notify/issues/92
      - name: Slack Notification if failed
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_MESSAGE: "!!!BUILD FAILED!!!"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      - name: Slack Notification if succed
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_MESSAGE: "Build success"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
